FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
WORKDIR /app
EXPOSE 5000
EXPOSE 5001

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY ["PriceHub.Service.csproj", "."]
RUN dotnet restore "PriceHub.Service.csproj"
COPY . .
RUN dotnet build "PriceHub.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "PriceHub.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "PriceHub.Service.dll"]
